CAMEL-17907: Add camel-infinispan-starter test
apache/camel-spring-boot pull request #514
Opened 2022-04-11 12:33 UTC by Croway

2022-04-12 12:18 UTC, davsclaus requested changes

2022-04-12 12:18 UTC, davsclaus commented on components-starter/camel-infinispan-starter/pom.xml
> +      <version>${project.version}</version>
For all <groupId>org.apache.camel</groupId>
Then you MUST use <version>${camel-version}</version>

As otherwise we cannot release camel-spring-boot due to build error during release.

2022-04-12 14:54 UTC, Croway commented on components-starter/camel-infinispan-starter/pom.xml
> +      <version>${project.version}</version>
thanks for the heads-up, and I'm sorry for trobule

2022-04-20 05:46 UTC, oscerd approved these changes

2022-04-20 07:51 UTC, davsclaus commented on components-starter/camel-infinispan-starter/pom.xml
> +      <version>${project.version}</version>
There is one more missing in the pom.xml at the test-spring5, can you fix that

2022-04-21 05:14 UTC, davsclaus approved these changes

2022-04-21 05:14 UTC, merged