Use commons-lang for aws2-sqs-starter
apache/camel-spring-boot pull request #529
Opened 2022-04-16 23:56 UTC by cunningt

Was getting a class not found error on org.testcontainers.shaded.org.apache.commons.lang.RandomStringUtils - replace with commons-lang version and add in commons-lang dependency

2022-04-17 06:28 UTC, davsclaus requested changes

2022-04-17 06:28 UTC, davsclaus commented on components-starter/camel-aws2-sqs-starter/pom.xml
> +      <version>${commons-lang-version}</version>
It seems its only used for testing, can you use <scope>test</scope>
And can you maybe use commons lang3 as the one you use now is legacy

2022-04-17 15:06 UTC, cunningt commented on components-starter/camel-aws2-sqs-starter/pom.xml
> +      <version>${commons-lang-version}</version>
Changed scope to test, changed to use commons-lang3 version

2022-04-18 05:30 UTC, davsclaus approved these changes

2022-04-18 05:30 UTC, merged